# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-monitor-lite" do
  name "claude-monitor-lite"
  desc "Lightweight menu bar monitor for Claude usage"
  homepage "https://github.com/wickes1/claude-monitor-lite"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-monitor-lite"

  on_macos do
    on_intel do
      url "https://github.com/wickes1/claude-monitor-lite/releases/download/v#{version}/claude-monitor-lite_Darwin_x86_64.tar.gz"
      sha256 "f396149c255f934a972048da9027ac7580033fd93cbf7cd809f6fa7c95e5980e"
    end
    on_arm do
      url "https://github.com/wickes1/claude-monitor-lite/releases/download/v#{version}/claude-monitor-lite_Darwin_arm64.tar.gz"
      sha256 "7458608d1e7d09f165bd70ca857f0cbdb5b6ffd36bb6250dccf3c45f5c5c5dfb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-monitor-lite"]
    end
  end

  # No zap stanza required
end
