# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-monitor-lite" do
  name "claude-monitor-lite"
  desc "Lightweight menu bar monitor for Claude usage"
  homepage "https://github.com/wickes1/claude-monitor-lite"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-monitor-lite"

  on_macos do
    on_intel do
      url "https://github.com/wickes1/claude-monitor-lite/releases/download/v#{version}/claude-monitor-lite_Darwin_x86_64.tar.gz"
      sha256 "beedfc8b85a3d547badf6a0224a1507f04c96bf26548b1e1909a61eed13ec2e1"
    end
    on_arm do
      url "https://github.com/wickes1/claude-monitor-lite/releases/download/v#{version}/claude-monitor-lite_Darwin_arm64.tar.gz"
      sha256 "d558b0d30e91cc7337f2dd7249ab62a5920997ecb0eccf52d1332890daa18271"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-monitor-lite"]
    end
  end

  # No zap stanza required
end
