# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-monitor-lite" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "d67179da92fc40d049ea3830e31eebaa05ba7e0ce69ea1b0dd98fb339c0ec721"
      url "https://github.com/wickes1/claude-monitor-lite/releases/download/v#{version}/claude-monitor-lite_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d073f08e0f52c6237f45aaffc2c9656842099dcb0f2fa03fe77d7108cf2c3763"
      url "https://github.com/wickes1/claude-monitor-lite/releases/download/v#{version}/claude-monitor-lite_Darwin_arm64.tar.gz"
    end
  end

  name "claude-monitor-lite"
  desc "Lightweight menu bar monitor for Claude usage"
  homepage "https://github.com/wickes1/claude-monitor-lite"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-monitor-lite"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-monitor-lite"]
    end
  end

  # No zap stanza required

end
