# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JoplinMcp < Formula
  desc "MCP server connecting AI assistants to Joplin for note management"
  homepage "https://github.com/wickes1/joplin-mcp"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wickes1/joplin-mcp/releases/download/v0.2.0/joplin-mcp_Darwin_x86_64.tar.gz"
      sha256 "3f45961e97403103e4c247d8e95621a195c19961ce99efa958227e864611dd72"

      define_method(:install) do
        bin.install "joplin-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wickes1/joplin-mcp/releases/download/v0.2.0/joplin-mcp_Darwin_arm64.tar.gz"
      sha256 "819a11c1d18da528ae836e4ea5800329c46f1d067adeff6b2debc5b8e2d392ee"

      define_method(:install) do
        bin.install "joplin-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickes1/joplin-mcp/releases/download/v0.2.0/joplin-mcp_Linux_x86_64.tar.gz"
      sha256 "2a9cf7690c59b7ad860e46fc4618b7258694bb4fb3f22f3304f3d645558b7e82"
      define_method(:install) do
        bin.install "joplin-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wickes1/joplin-mcp/releases/download/v0.2.0/joplin-mcp_Linux_arm64.tar.gz"
      sha256 "e6a41334c9428df875a359767d011a565472265b1a75a09fc17f9da4ad5eaeba"
      define_method(:install) do
        bin.install "joplin-mcp"
      end
    end
  end

  test do
    assert_match "JOPLIN_TOKEN", shell_output("#{bin}/joplin-mcp 2>&1", 1)
  end
end
